SHELL=/bin/bash
# findMaxFreq png2gray Rotate_anticlockwise flip left2right prime_Factor super_Impose isSubString
# plist=findMaxFreq
p=findMaxFreq

all:
	make clean
	make run
clean:
	rm -f *.out
run:
	g++ $(p).cpp -o $(p).out
	./$(p).out


